version: '3.8'

services:
  db:
    image: egain_database
    container_name: egain_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: egain_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional

  pgadmin:
    image: pgadmin_egain
    container_name: egain_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: aranzamendeza10@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
